### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by dog1cool** [HypeRayy/pogphone-discord-bot#2]
i keep getting this error 
There was issue parsing commands.json!
(node:238) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
There was issue parsing events.json!
There was issue parsing settings.json!
There was issue parsing players.json!
There was issue parsing servers.json!
There was issue parsing serverVars.json!
There was issue parsing globalVars.json!
I am kinda new and new some help the files above are blank only {} i did settings.json that i put token owner id and bot id. Please help me.

**Comment by HypeRayy** [comment]
Have you tried redownloading the files? Ninety percent of the email I get about this particular issue are solved by doing this.

**Comment by HypeRayy** [comment]
Okay, I am going to assume your problem was solved as you have not replied at all. You can reply if you would like to continue this issue,
